# Generated by Django 3.2 on 2022-04-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='newsletter',
        ),
    ]
