# Generated by Django 3.2 on 2022-03-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='extra_feature',
        ),
        migrations.DeleteModel(
            name='ExtaFeature',
        ),
    ]
