# Generated by Django 3.2 on 2022-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_20220327_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='size',
        ),
        migrations.AddField(
            model_name='tree',
            name='height_in',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='trunk_width_in',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
