# Generated by Django 3.2 on 2022-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20220327_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='image_disclaimer',
            field=models.CharField(blank=True, choices=[('standarised', 'This is an image of a typical tree                         of this size and shape. We grow and                         sell many nearly identical specimen.                         The product that you will purchase will be                         very similar to the one on the photograph.'), ('unique', 'This is an image of the specimen that is being for sale')], default='standarised', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
