# Generated by Django 3.2 on 2022-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20220327_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviroment',
            name='icon_fontawsome',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='tree',
            name='feature',
        ),
        migrations.AddField(
            model_name='tree',
            name='feature',
            field=models.ManyToManyField(blank=True, to='trees.Feature'),
        ),
    ]
