# Generated by Django 3.2 on 2022-03-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_auto_20220327_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='image_description',
            new_name='image_alt',
        ),
    ]
