# Generated by Django 3.2 on 2022-03-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_tree_leaves_or_needles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='trunk_width_in',
            new_name='trunk_circumference',
        ),
    ]
