# Generated by Django 3.2 on 2022-03-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_rename_trunk_width_in_tree_trunk_circumference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviroment',
            old_name='icon_fontawsome',
            new_name='icon_class',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='icon_fontawsome',
            new_name='icon_class',
        ),
    ]
