# Generated by Django 3.2 on 2022-04-10 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_auto_20220329_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='current_stock',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(default='name', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
