# Generated by Django 3.2 on 2022-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_auto_20220410_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
