# Generated by Django 3.2 on 2022-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_alter_tree_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='image_disclaimer',
            field=models.CharField(blank=True, choices=[('This is an image of a typical tree of this size and shape. We grow and         sell many nearly identical specimen. The product that         you will purchase will be very similar to the one on the         photograph.', 'standarised'), ('unique', 'This is an image of the specimen that is being for sale')], default='standarised', max_length=254, null=True),
        ),
    ]
