# Generated by Django 3.2 on 2022-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_alter_tree_image_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='image_disclaimer',
            field=models.CharField(blank=True, choices=[('This is an image of a typical tree of this size and shape. We grow and           sell many nearly identical specimen. The product that           you will purchase will be very similar to the one on the           photograph.', 'standarised'), ('This is an image of the specimen that is being for sale.           The look of the tree may change over the time Due to their           nature trees grow and whilst in our care may need pruning,           this means the tree that you receive may differ in size to           that given in the description. The appearance of the tree may           vary depending on the season.', 'unique')], default='standarised', max_length=400, null=True),
        ),
    ]
